spring:
  application:
    name: transaction-service

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=db_transaksi
    username: SA
    password: P@$$w0rd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8882/eureka/
  instance:
    hostname: localhost

integration:
  exmcs:
    log-transaction-service:
      saving-log-transaction:
        url: http://log-service/log-transaction/save
    company-service:
      getting-employee-data:
        url: http://company-service/api-fe/get-employee

