# Konfigurasi default
server:
  port: 8008

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: COMPANY-SERVICE
          uri: lb://company-service
          predicates:
            - Path=/api-fe/**
        - id: TRANSACTION-SERVICE
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
        - id: LOG-SERVICE
          uri: lb://log-service
          predicates:
            - Path=/log/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info
  endpoint:
    info:
      enabled: true

# Konfigurasi profil Docker
---
spring:
  config:
    activate:
      on-profile:
        - docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8882/eureka/
  instance:
    hostname: eureka-server