# Konfigurasi default
server:
  port: 8008

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: COMPANY-SERVICE
          uri: lb://company-service
          predicates:
            - Path=/api-fe/**
        - id: TRANSACTION-SERVICE
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
        - id: LOG-SERVICE
          uri: lb://log-service
          predicates:
            - Path=/log/**
        - id: LOGIN-SERVICE
          uri: lb://login-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8882/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info
  endpoint:
    info:
      enabled: true

jwt:
  secret-key:
    value: exmcsJwtSecretKeyexmcsJwtSecretKeyexmcsJwtSecretKeyexmcsJwtSecretKeyexmcsJwtSecretexmcsJwtSecret

logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG

# Konfigurasi profil local
---
spring:
  config:
    activate:
      on-profile:
        - local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8882/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

