server:
  port: 8882

spring:
  application:
    name: registry-service


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile:
        - docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8882/eureka
  instance:
    hostname: eureka-server
