spring:
  application:
    name: log-service

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=db_log
    username: SA
    password: P@$$w0rd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8882/eureka/
  instance:
    hostname: localhost
